server.port=8080
server.address=0.0.0.0
spring.application.name=collegeservices-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/collegeservices_db
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
app.jwt.secret=nec_college_faculty_service_management_secure_jwt_token_secret_key_2026_xyz
app.jwt.expiration-ms=86400000

# Logging
logging.level.com.nec.collegeservices=DEBUG
logging.level.org.springframework.security=INFO

# Web Push VAPID Configuration
app.vapid.public-key=BOhTIhLV2PbraKWzqTrUOz88Q33IuzrZ-nan8jWt4zsOzHkGuE4-AE0DRC94biUAEtTusgd77hOCMM09xrgOBIU
app.vapid.subject=mailto:admin@nec.edu.in
app.vapid.private-key=${VAPID_PRIVATE_KEY:}
